"use client";
import Menu from "@/components/Menu";
import Footer from "@/components/Footer";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Lenis as ReactLenis } from "@studio-freight/react-lenis";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactLenis root>
          <Menu />
          {children}
          <Footer />
        </ReactLenis>
      </body>
    </html>
  );
}
